version: '3.7'
services:
    myproxy:
        build:
            context: .
            dockerfile: myproxy
        #networks:
                #- myproxy
        ports:
            - 80:80
            - 443:443
    mysite:
        build:
           context: .
           dockerfile: prismaweb

        #networks:
            #- myproxy
        ports:
            - 8080:80

            
#networks:
    #myproxy:
        #external:
            #name: myproxy
      

    
